DROP DATABASE IF EXISTS gym_records;
CREATE DATABASE IF NOT EXISTS gym_records;
USE gym_records;

CREATE TABLE IF NOT EXISTS SOCIOS (
  Socio_ID INT NOT NULL,
  nombre VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  Telefono VARCHAR(20) NULL,
  PRIMARY KEY (Socio_ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS CIUDADES (
  Ciudad_ID VARCHAR(10) NOT NULL,
  Ciudad_Sede VARCHAR(100) NOT NULL,
  PRIMARY KEY (Ciudad_ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS SEDES (
  Sede_ID VARCHAR(10) NOT NULL,
  Gimnasio_Sede VARCHAR(100) NOT NULL,
  Ciudad_ID VARCHAR(10) NOT NULL,
  PRIMARY KEY (Sede_ID),
  CONSTRAINT fk_SEDES_CIUDADES
    FOREIGN KEY (Ciudad_ID)
    REFERENCES CIUDADES (Ciudad_ID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PLANES_ENTRENAMIENTO (
  Plan_Entrenamiento_ID VARCHAR(10) NOT NULL,
  Plan_Entrenamiento VARCHAR(100) NOT NULL,
  PRIMARY KEY (Plan_Entrenamiento_ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ESPECIALIDAD_ENTRENADORES (
  Especialidad_ID VARCHAR(10) NOT NULL,
  Nombre_Especialidad VARCHAR(100) NOT NULL,
  PRIMARY KEY (Especialidad_ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ENTRENADORES (
  Entrenador_ID VARCHAR(10) NOT NULL,
  Nombre_Entrenador VARCHAR(100) NOT NULL,
  Especialidad_ID VARCHAR(10) NOT NULL,
  PRIMARY KEY (Entrenador_ID),
  CONSTRAINT fk_ENTRENADORES_ESPECIALIDAD
    FOREIGN KEY (Especialidad_ID)
    REFERENCES ESPECIALIDAD_ENTRENADORES (Especialidad_ID)
    ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS SOCIO_PLAN_ENTRENAMIENTO (
  Plan_ID INT NOT NULL,
  Socio_ID INT NOT NULL,
  Plan_Entrenamiento_ID VARCHAR(10) NOT NULL,
  Entrenador_ID VARCHAR(10) NOT NULL,
  Sede_ID VARCHAR(10) NOT NULL,
  PRIMARY KEY (Plan_ID),
  CONSTRAINT fk_SPE_SOCIOS
    FOREIGN KEY (Socio_ID)
    REFERENCES SOCIOS (Socio_ID)
    ON UPDATE CASCADE,
  CONSTRAINT fk_SPE_PLANES
    FOREIGN KEY (Plan_Entrenamiento_ID)
    REFERENCES PLANES_ENTRENAMIENTO (Plan_Entrenamiento_ID)
    ON UPDATE CASCADE,
  CONSTRAINT fk_SPE_ENTRENADORES
    FOREIGN KEY (Entrenador_ID)
    REFERENCES ENTRENADORES (Entrenador_ID)
    ON UPDATE CASCADE,
  CONSTRAINT fk_SPE_SEDES
    FOREIGN KEY (Sede_ID)
    REFERENCES SEDES (Sede_ID)
    ON UPDATE CASCADE
) ENGINE = InnoDB;